apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
 name: kafka-cluster
 namespace: kafka
 annotations:
 strimzi.io/kraft: disabled # ZooKeeper-based
 strimzi.io/node-pools: enabled # Node pools enabled
spec:
 kafka | spec.kafka:
 version: 3.7.0
 replicas: 3
 config:
 # Ensure no unsupported configs like inter.broker.protocol.version
 zookeeper | spec.zookeeper:
 replicas: 3
 entityOperator | spec.entityOperator:
 topicOperator: {}
 userOperator: {}