apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-zookeeper
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/resources
spec:
  project: default
  source:
    repoURL: https://github.com/immxmmi/kafka-meetup.git
    targetRevision: main
    path: kafka-zookeeper/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-zookeeper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
