kubectl create namespace kafka-zookeeper

https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.40.0
kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka-zookeeper' -n kafka-zookeeper